### ISSUE TITLE
Generación de demasiadas estadísticas

### ISSUE THREAD

**Issue by smorenodp** [afkim11/TFG#6]
Cada vez que se para un robot y se reasignan las víctimas se generarán todas las estadísticas que normalmente por cada robot parado. Esto es porque antes de pararlo ya se tienen todas asignadas así que se generan pero al reasignarlas se vuelven a crear otras nuevas.

**Comment by Yarichi** [comment]
Cada vez que se para un robot y se reasignan las víctimas se generarán todas las estadísticas que normalmente por cada robot parado. Esto es porque antes de pararlo ya se tienen todas asignadas así que se generan pero al reasignarlas se vuelven a crear otras nuevas.
